In [1]:
import pandas as pd

In [2]:
credits=pd.read_csv(r'Datasets\tmdb_5000_credits.csv')
movies=pd.read_csv(r'Datasets\tmdb_5000_movies.csv')

In [3]:
credits.columns

Index(['movie_id', 'title', 'cast', 'crew'], dtype='object')

In [4]:
movies.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count'],
      dtype='object')

In [5]:
movies = movies.merge(credits,on='title')

In [6]:
movies = movies[['original_title','overview','genres']]

In [7]:
movies.head()

,original_title,overview,genres
0,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam..."
1,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""..."
2,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam..."
3,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam..."
4,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam..."

In [8]:
import ast

def convert(text):
    L = []
    for i in ast.literal_eval(text):
        L.append(i['name'])
    return L

movies['genres'] = movies['genres'].apply(convert)

In [9]:
movies.head()

,original_title,overview,genres
0,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]"
1,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]"
2,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]"
3,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]"
4,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]"

In [10]:
movies.shape

(4809, 3)

In [11]:
movies.isnull().sum()

original_title    0
overview          3
genres            0
dtype: int64

In [12]:
movies.dropna(inplace=True)

Text Preprocessing

1.lower_casing

In [13]:
movies['overview']=movies['overview'].str.lower()

2.Remove Punction Marks

In [14]:
import string
exclude=string.punctuation

In [15]:
# Not to do because takes more time
def remove_punc1(text):
    for ch in exclude:
        text=text.replace(ch,'')
    return text

In [16]:
# Use this 
def remove_punc2(text):
    return text.translate(str.maketrans('','',exclude))

In [17]:
movies['overview']=movies['overview'].apply(remove_punc2)

3.Spelling Correction

In [18]:
from textblob import TextBlob

In [19]:
# i am not using for this dataset not reqired 
def correct_text(text):
    return str(TextBlob(text).correct())

4.Removal of Stop words

In [20]:
import nltk

In [21]:
from nltk.corpus import stopwords
stop_words=set(stopwords.words('english'))

def remove_stopwords(text):
     return " ".join(
        word for word in text.split()
        if word.lower() not in stop_words
    )

In [22]:
movies['overview'] = movies['overview'].apply(remove_stopwords)

5.Handling Emojis

In [23]:
# not using for this dataset
# for removing emojis
import re
def remove_emoji(text):
    emoji_pattern=re.compile("[" \
    u"\U0001F600-\U0001F64F"
    u"\U0001F300-\U0001F5FF"
    u"\U0001F680-\U0001F6FF"
    u"\U0001F1E0-\U0001F1FF"
    u"\U00002702-\U000027B0"
    u"\U000024C2-\U0001F251"
    "]+",flags=re.UNICODE)
    return emoji_pattern.sub(r'',text)

In [24]:
# for replacing emoji
import emoji
print(emoji.demojize('Python is 🔥'))

Python is :fire:

6.Tokenisation

By using NLTK

In [25]:
import nltk

nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to C:\Users\Rishikesh
[nltk_data]     Reddy\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to C:\Users\Rishikesh
[nltk_data]     Reddy\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [29]:
# by using NLTK
from nltk.tokenize import word_tokenize,sent_tokenize
sent1='I am going to Bangalore'
sent2="We're here to help! mail us at nsk@gmail.com" 
word_tokenize(sent1)

['I', 'am', 'going', 'to', 'Bangalore']

In [30]:
word_tokenize(sent2)

['We',
 "'re",
 'here',
 'to',
 'help',
 '!',
 'mail',
 'us',
 'at',
 'nsk',
 '@',
 'gmail.com']

In [27]:
text="""Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. Suspendisse lectus tortor, dignissim sit amet, adipiscing nec, ultricies sed, dolor.
Cras elementum ultrices diam. Maecenas ligula massa, varius a, semper congue, euismod non, mi. Proin porttitor, orci nec nonummy molestie, enim est eleifend mi.
Nullam malesuada erat ut turpis. Suspendisse urna nibh, viverra non, semper suscipit, posuere a, pede. Donec nec justo eget felis facilisis fermentum."""

In [28]:
sent_tokenize(text)

['Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
 'Sed non risus.',
 'Suspendisse lectus tortor, dignissim sit amet, adipiscing nec, ultricies sed, dolor.',
 'Cras elementum ultrices diam.',
 'Maecenas ligula massa, varius a, semper congue, euismod non, mi.',
 'Proin porttitor, orci nec nonummy molestie, enim est eleifend mi.',
 'Nullam malesuada erat ut turpis.',
 'Suspendisse urna nibh, viverra non, semper suscipit, posuere a, pede.',
 'Donec nec justo eget felis facilisis fermentum.']

BY uisng Spacy

In [32]:
import spacy
nlp=spacy.load('en_core_web_sm')

In [33]:
doc1=nlp(sent1)
doc2=nlp(sent2)

In [35]:
for token in doc2:
    print(token)

We
're
here
to
help
!
mail
us
at
nsk@gmail.com

In [36]:
movies['tokens'] = movies['overview'].apply(
    lambda x: [token.text for token in nlp(x)]
)

7.Stemming(making the inflected words to root form)

In [39]:
from nltk.stem import PorterStemmer

ps = PorterStemmer()

movies['tokens'] = movies['tokens'].apply(
    lambda tokens: [ps.stem(word) for word in tokens]
)

Lemmatisation(use this or stemming)

In [ ]:
#by spacy
sent3='Running run jogging jog'
doc3=nlp(sent3)
lemmas = [token.lemma_ for token in doc3]
print(lemmas)

['run', 'run', 'jog', 'jog']

In [45]:
#by NLTK
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()
words = ["players", "playing", "studies", "cars"]
lemmas = [lemmatizer.lemmatize(word) for word in words]
print(lemmas)

['player', 'playing', 'study', 'car']