In [2]:
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [4]:
df=pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [5]:
df.drop(columns=['id','Unnamed: 32'],inplace=True)
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [6]:
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

In [7]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [8]:
X_train

array([[ 0.18990433,  1.45123696,  0.12764265, ..., -0.07968081,
        -0.26510666, -0.81063124],
       [ 0.34288364, -1.44860308,  0.27308555, ..., -0.17245655,
        -0.9096464 , -0.51423719],
       [-0.09007668,  0.72569745, -0.04294888, ...,  0.81405887,
         0.30888645,  0.54946267],
       ...,
       [-1.41695575, -1.22839141, -1.36031788, ..., -0.98625446,
         0.63275965,  0.06710711],
       [-0.49705939,  0.61211458, -0.49771992, ...,  0.09040806,
         0.13572652,  0.50826505],
       [-0.47108177, -0.80187617, -0.3807788 , ...,  0.91920472,
         1.75990253,  2.32725476]], shape=(455, 30))

In [9]:
y_train

542    B
209    B
196    M
271    B
553    B
      ..
360    B
460    M
63     B
88     B
5      M
Name: diagnosis, Length: 455, dtype: object

In [10]:
# Label Encoder
encoder=LabelEncoder()
y_train=encoder.fit_transform(y_train)
y_test=encoder.transform(y_test)

In [21]:
# numpy arrays to pytorch tensors
X_train_tensor=torch.from_numpy(X_train).float()
X_test_tensor=torch.from_numpy(X_test).float()
y_train_tensor=torch.from_numpy(y_train).float().view(-1,1)
y_test_tensor=torch.from_numpy(y_test).float().view(-1,1)

In [12]:
y_train_tensor.shape

torch.Size([455])

In [19]:
# creating model
class Model(nn.Module):
    def __init__(self,num_features):
        super().__init__()
        self.network=nn.Sequential(
            nn.Linear(num_features,3),  #------> Takes input features and gives 3 outputs(3 nodes)
            nn.ReLU(),
            nn.Linear(3,1),              #-----> Takes 3 input features and gives 1 output(1 node)
            nn.Sigmoid()
        )

    def forward(self,features):
        out=self.network(features)
        return out

In [13]:
# params
learning_rate=0.1
epochs=25

In [14]:
loss_function=nn.BCELoss()

In [22]:
# Training Pipeline

#create model
model=Model(X_train_tensor.shape[1])

#define the optimizer
optimizer=torch.optim.SGD(model.parameters(),lr=learning_rate)

# define in loop(epochs)
for epoch in range(epochs):

    #forward pass
    y_pred=model(X_train_tensor)
    
    #loss calculation
    loss=loss_function(y_pred,y_train_tensor)

    # clear gradients
    optimizer.zero_grad()

    #backward pass
    loss.backward()

    # weights and bais update
    optimizer.step()

    #prit loss 
    print(f"Epoch:{epoch+1},loss:{loss.item()}")

Epoch:1,loss:0.7047444581985474
Epoch:2,loss:0.6915176510810852
Epoch:3,loss:0.6779444217681885
Epoch:4,loss:0.663853645324707
Epoch:5,loss:0.6492852568626404
Epoch:6,loss:0.6341373920440674
Epoch:7,loss:0.6184147596359253
Epoch:8,loss:0.6021106243133545
Epoch:9,loss:0.5852112770080566
Epoch:10,loss:0.5677804350852966
Epoch:11,loss:0.5499036312103271
Epoch:12,loss:0.5316634178161621
Epoch:13,loss:0.513140857219696
Epoch:14,loss:0.4945012032985687
Epoch:15,loss:0.4758577346801758
Epoch:16,loss:0.4573758840560913
Epoch:17,loss:0.4391592741012573
Epoch:18,loss:0.42136144638061523
Epoch:19,loss:0.4041493535041809
Epoch:20,loss:0.38760805130004883
Epoch:21,loss:0.3717767596244812
Epoch:22,loss:0.3567095100879669
Epoch:23,loss:0.34243035316467285
Epoch:24,loss:0.32897812128067017
Epoch:25,loss:0.31635594367980957

In [26]:
# Evaluation
with torch.no_grad():
    y_pred=model.forward(X_test_tensor)
    y_pred=(y_pred>0.62).float()
    acc=(y_pred==y_test_tensor).float().mean()
    print(f"Accuracy:{acc.item()}")

Accuracy:0.9298245906829834