In [3]:
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [4]:
df=pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [5]:
df.drop(columns=['id','Unnamed: 32'],inplace=True)
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [6]:
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

In [7]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [8]:
X_train

array([[-0.13138057,  0.95255756, -0.18528044, ..., -0.65064375,
        -0.41363397, -0.79999744],
       [ 0.77039865,  0.07472113,  0.67675423, ..., -0.45880844,
        -0.59387845, -1.32679575],
       [ 1.52934949,  0.9479006 ,  1.50993247, ...,  1.03300748,
        -0.51707863, -0.45148358],
       ...,
       [-1.9906701 , -1.32935145, -1.94917976, ..., -1.74115601,
         0.0408956 ,  0.5043788 ],
       [-0.33022009, -0.65409266, -0.37467608, ..., -0.48936224,
         0.18509119, -0.80214545],
       [-0.74470247, -0.87296965, -0.75956379, ..., -0.45272808,
        -0.36034429, -0.90095369]], shape=(455, 30))

In [9]:
y_train

545    B
157    B
389    M
6      M
183    B
      ..
559    B
20     B
101    B
195    B
137    B
Name: diagnosis, Length: 455, dtype: object

In [10]:
# Label Encoder
encoder=LabelEncoder()
y_train=encoder.fit_transform(y_train)
y_test=encoder.transform(y_test)

In [11]:
# numpy arrays to pytorch tensors
X_train_tensor=torch.from_numpy(X_train).float()
X_test_tensor=torch.from_numpy(X_test).float()
y_train_tensor=torch.from_numpy(y_train).float().view(-1,1)
y_test_tensor=torch.from_numpy(y_test).float().view(-1,1)

In [12]:
y_train_tensor.shape

torch.Size([455, 1])

In [1]:
from torch.utils.data import Dataset,DataLoader
class CustomDataset(Dataset):
    def __init__(self,features,labels):
        self.features=features
        self.labels=labels

    def __len__(self):
        return self.features.shape[0]

    def __getitem__(self, index):  
        return self.features[index],self.labels[index]

In [13]:
train_dataset=CustomDataset(X_train_tensor,y_train_tensor)
test_dataset=CustomDataset(X_test_tensor,y_test_tensor)

In [14]:
train_loader=DataLoader(train_dataset,batch_size=32,shuffle=True)
test_loader=DataLoader(test_dataset,batch_size=32,shuffle=True)

In [15]:
# creating model
class Model(nn.Module):
    def __init__(self,num_features):
        super().__init__()
        self.network=nn.Sequential(
            nn.Linear(num_features,3),  #------> Takes input features and gives 3 outputs(3 nodes)
            nn.ReLU(),
            nn.Linear(3,1),              #-----> Takes 3 input features and gives 1 output(1 node)
            nn.Sigmoid()
        )

    def forward(self,features):
        out=self.network(features)
        return out

In [16]:
# params
learning_rate=0.1
epochs=25

In [17]:
loss_function=nn.BCELoss()

In [18]:
# Training Pipeline

#create model
model=Model(X_train_tensor.shape[1])

#define the optimizer
optimizer=torch.optim.SGD(model.parameters(),lr=learning_rate)

# define in loop(epochs)
for epoch in range(epochs):
    for batch_features,batch_labels in train_loader:
        #forward pass
        y_pred=model(batch_features)
        
        #loss calculation
        loss=loss_function(y_pred,batch_labels.view(-1,1))

        # clear gradients
        optimizer.zero_grad()

        #backward pass
        loss.backward()

        # weights and bais update
        optimizer.step()

    #prit loss 
    print(f"Epoch:{epoch+1},loss:{loss.item()}")

Epoch:1,loss:0.6245642304420471
Epoch:2,loss:0.2946845591068268
Epoch:3,loss:0.3632052540779114
Epoch:4,loss:0.0624600350856781
Epoch:5,loss:0.03624977916479111
Epoch:6,loss:0.11144077032804489
Epoch:7,loss:0.03724184259772301
Epoch:8,loss:0.017355812713503838
Epoch:9,loss:0.06458581984043121
Epoch:10,loss:0.11913128942251205
Epoch:11,loss:0.5746220946311951
Epoch:12,loss:0.03330034390091896
Epoch:13,loss:0.004961300641298294
Epoch:14,loss:0.0326700396835804
Epoch:15,loss:0.13974343240261078
Epoch:16,loss:0.0871596410870552
Epoch:17,loss:0.037440985441207886
Epoch:18,loss:0.007418750319629908
Epoch:19,loss:0.030801070854067802
Epoch:20,loss:0.08437804877758026
Epoch:21,loss:0.06710637360811234
Epoch:22,loss:0.034163814038038254
Epoch:23,loss:0.026422632858157158
Epoch:24,loss:0.08236045390367508
Epoch:25,loss:0.001922554220072925

In [24]:
# Evaluation using test loader
model.eval()  # Set the model to evaluation mode
acc_list=[]

with torch.no_grad():
    for batch_features,batch_labels in test_loader:
        # Forward pass
        y_pred=model(batch_features)
        y_pred=(y_pred>0.7).float()

        # cal accuracy for current batch
        batch_accuracy=(y_pred.view(-1)==batch_labels).float().mean().item()
        acc_list.append(batch_accuracy)

    # Calculate overall accuracy
    overall_acc=sum(acc_list)/len(acc_list)
    print(f"Accuracy:{overall_acc:.4f}")

Accuracy:0.5429